### ISSUE TITLE
I got an error while I run this script in Matlab console.

### ISSUE THREAD

**Issue by yuanyuxin0077** [slimgroup/WAVEFORM#1]
matrix_mode='explicit';
params=struct;
params.coef=[1 2;3 4];
solve_opts=LinSolveOpts();
A=opAbstractMatrix(matrix_mode,params,solve_opts);

**Comment by henryk-modzelewski** [comment]
It would help if attach the error trace.

**Comment by yuanyuxin0077** [comment]
It returns  an error：“If the class defines a superclass, all superclasses must be both a handle class, or all superclasses are not a handle class”

**Comment by yuanyuxin0077** [comment]
What's more, it seems missing some functions in the software "WAVEFORM" ,like "jacobi" and "kaczswp" etc.

**Comment by curtd** [comment]
Replying to @yuanyuxin0077:
> It returns an error：“If the class defines a superclass, all superclasses must be both a handle class, or all superclasses are not a handle class”

I should have mentioned this in the README. Replace the first line of the file 
```matlab
[SPOT directory]/@opSpot/opSpot.m
```

```matlab
classdef opSpot
```

with 
```matlab
classdef (HandleCompatible) opSpot
```

Alternatively, you can check out the copy of SPOT with this modification in place over at https://github.com/curtd/spot

**Comment by curtd** [comment]
Replying to @yuanyuxin0077 
> What's more, it seems missing some functions in the software "WAVEFORM" ,like "jacobi" and "kaczswp" etc.

This functionality was not part of the original paper and has not been included as a result.

**Comment by yuanyuxin0077** [comment]
Thank you very much!

**Comment by yuanyuxin0077** [comment]
Thank you very much!

发自我的 iPhone
